# Streamlit Secrets Configuration
# Save this as: .streamlit/secrets.toml

# Employee Admin Password
employee_admin_password = "admin123"

# Foundation Admin Password  
foundation_admin_password = "admin123"

# Payroll Admin Password
payroll_admin_password = "admin123"

# Master Admin Password (for all systems)
master_admin_password = "admin123"

# Optional: Database connections, API keys, etc.
# [connections.mysql]
# dialect = "mysql"
# host = "localhost"
# port = 3306
# database = "sap_migration"
# username = "admin"
# password = "your_db_password"

# [connections.api_keys]
# openai_api_key = "your_openai_key"
# other_api_key = "your_other_key"
